# Generated by Django 3.1.7 on 2021-03-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_144p',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_240p',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_360p',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_480p',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_720p',
        ),
        migrations.AddField(
            model_name='lesson',
            name='videoPath',
            field=models.CharField(default='', max_length=200),
        ),
    ]
